# Generated by Django 5.0.14 on 2025-10-28 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, help_text='Free text comments about the student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('comments', models.TextField(blank=True, help_text='Free text comments about the supervisor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Thesis title (can be added later)', max_length=500)),
                ('thesis_type', models.CharField(choices=[('bachelor', 'Bachelor Thesis'), ('master', 'Master Thesis'), ('project', 'Project Work'), ('other', 'Other')], default='bachelor', max_length=20)),
                ('phase', models.CharField(choices=[('first_contact', 'First Contact'), ('topic_discussion', 'Topic Discussion'), ('literature_research', 'Literature Research'), ('registered', 'Registered'), ('working', 'Working'), ('submitted', 'Submitted'), ('defended', 'Defended'), ('reviewed', 'Reviewed'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='first_contact', max_length=30)),
                ('date_first_contact', models.DateField(blank=True, help_text='Date of initial contact', null=True)),
                ('date_topic_selected', models.DateField(blank=True, help_text='When topic was finalized', null=True)),
                ('date_registration', models.DateField(blank=True, help_text='Official registration date', null=True)),
                ('date_deadline', models.DateField(blank=True, help_text='Submission deadline', null=True)),
                ('date_presentation', models.DateField(blank=True, help_text='Date of defense/presentation', null=True)),
                ('date_review', models.DateField(blank=True, help_text='Date of review completion', null=True)),
                ('date_final_discussion', models.DateField(blank=True, help_text='Final discussion date', null=True)),
                ('git_repository', models.URLField(blank=True, help_text="URL to student's git repository")),
                ('description', models.TextField(blank=True, help_text='General description of the thesis')),
                ('task_description', models.TextField(blank=True, help_text='Formal multi-paragraph task description defining scope and objectives')),
                ('review', models.TextField(blank=True, help_text='Formal multi-paragraph review of the completed thesis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(related_name='theses', to='theses.student')),
                ('supervisors', models.ManyToManyField(related_name='supervised_theses', to='theses.supervisor')),
            ],
            options={
                'verbose_name_plural': 'Theses',
                'ordering': ['-date_first_contact', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Comment text')),
                ('is_auto_generated', models.BooleanField(default=False, help_text='Was this comment auto-generated?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='theses.thesis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
