# Generated by Django 5.0.14 on 2025-10-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='ai_context',
            field=models.TextField(blank=True, help_text="Additional context for AI analysis (max 500 chars). E.g., 'Pure theory thesis, no implementation expected' or 'Focus on hardware development, code changes will be minimal'.", max_length=500),
        ),
        migrations.AddField(
            model_name='thesis',
            name='ai_summary_enabled',
            field=models.BooleanField(default=True, help_text='Enable AI-powered progress analysis in weekly reports. Disable if student does not consent to external AI processing.'),
        ),
    ]
