# Generated by Django 5.2.7 on 2025-10-27 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='comments',
        ),
        migrations.AddField(
            model_name='thesis',
            name='description',
            field=models.TextField(blank=True, help_text='General description of the thesis'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Comment text')),
                ('is_auto_generated', models.BooleanField(default=False, help_text='Was this comment auto-generated?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='theses.thesis')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
