# Generated by Django 5.0.14 on 2025-10-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0002_remove_thesis_comments_thesis_description_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='review',
            field=models.TextField(blank=True, help_text='Formal review of the completed thesis'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='task_description',
            field=models.TextField(blank=True, help_text='Formal task description for the thesis'),
        ),
    ]
