# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theses', '0002_thesis_ai_context_thesis_ai_summary_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Weekly Status Update')", max_length=200)),
                ('message', models.TextField(help_text='Template message text (supports Markdown)')),
                ('description', models.TextField(blank=True, help_text='Optional description of when to use this template')),
                ('is_active', models.BooleanField(default=True, help_text='Is this template available for use?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_message', models.TextField(help_text='The message/prompt sent to the student')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_responded', models.BooleanField(default=False, help_text='Has the student responded?')),
                ('first_response_at', models.DateTimeField(blank=True, help_text='When student first responded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_request', to='theses.comment')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='theses.thesis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
