# Generated by Django 5.0.14 on 2025-10-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_thesis_review_thesis_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='review',
            field=models.TextField(blank=True, help_text='Formal multi-paragraph review of the completed thesis'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='task_description',
            field=models.TextField(blank=True, help_text='Formal multi-paragraph task description defining scope and objectives'),
        ),
    ]
