# Generated by Django - Data Migration for Initial Feedback Templates

from django.db import migrations


def create_initial_templates(apps, schema_editor):
    """Create initial feedback request templates"""
    FeedbackTemplate = apps.get_model('theses', 'FeedbackTemplate')

    templates = [
        {
            'name': 'Weekly Status Update',
            'description': 'Standard weekly check-in for ongoing theses',
            'message': '''Please provide a summary of your progress this week.

## What have you achieved last week?
[Enter your accomplishments here]

## What are currently the largest challenges?
[Describe any obstacles or difficulties you're facing]

## What are the plans for the coming week?
[Outline your goals and tasks for next week]

## Any additional comments or questions?
[Optional: Any other information you'd like to share]
'''
        },
        {
            'name': 'Monthly Progress Report',
            'description': 'Comprehensive monthly update for longer-term tracking',
            'message': '''Please provide a comprehensive monthly progress report.

## Summary of Work Completed
[Describe the major accomplishments and milestones reached this month]

## Current Status
[Explain where you are in the overall thesis timeline]

## Challenges and Solutions
[Detail any significant challenges faced and how you addressed them]

## Plan for Next Month
[Outline your objectives and planned activities for the coming month]

## Resource Needs
[Mention any additional resources, support, or guidance you need]
'''
        },
        {
            'name': 'Pre-Submission Check',
            'description': 'Final status check before thesis submission',
            'message': '''As you approach submission, please provide the following information:

## Completion Status
- [ ] Thesis writing completed
- [ ] All figures/tables finalized
- [ ] Bibliography complete and formatted
- [ ] Proofreading/editing done
- [ ] Formatting according to guidelines

## Submission Timeline
[Provide your planned submission date and any concerns]

## Outstanding Items
[List any remaining tasks or open questions]

## Final Review Requests
[Specify what you'd like reviewed before final submission]
'''
        },
        {
            'name': 'Post-Meeting Follow-Up',
            'description': 'Follow-up after supervision meetings',
            'message': '''Thank you for our recent meeting. Please provide the following:

## Meeting Summary
[Briefly summarize the key points discussed]

## Action Items
[List the specific tasks you committed to completing]

## Timeline for Action Items
[Indicate when you plan to complete each task]

## Questions or Clarifications
[Any points from the meeting that need clarification]
'''
        },
        {
            'name': 'Research Phase Update',
            'description': 'For theses in early research/literature review phase',
            'message': '''Please provide an update on your research progress.

## Literature Review Progress
[Describe key papers/resources you've reviewed]

## Research Questions
[State or refine your research questions/hypotheses]

## Methodology Considerations
[Discuss your planned approach and any methodology decisions]

## Next Steps in Research Phase
[Outline what you'll focus on next in your research]
'''
        },
        {
            'name': 'Implementation Status',
            'description': 'For theses with practical/implementation components',
            'message': '''Please update on your implementation progress.

## Implementation Progress
[Describe what you've built/developed so far]

## Technical Challenges
[Explain any technical difficulties encountered]

## Testing and Validation
[Describe your testing approach and results]

## Code/Repository Status
[Provide link and status of your code repository]

## Next Implementation Steps
[Outline your development priorities for the coming period]
'''
        },
    ]

    for template_data in templates:
        FeedbackTemplate.objects.get_or_create(
            name=template_data['name'],
            defaults={
                'description': template_data['description'],
                'message': template_data['message'],
                'is_active': True,
            }
        )


def remove_initial_templates(apps, schema_editor):
    """Remove the initial templates if migration is reversed"""
    FeedbackTemplate = apps.get_model('theses', 'FeedbackTemplate')

    template_names = [
        'Weekly Status Update',
        'Monthly Progress Report',
        'Pre-Submission Check',
        'Post-Meeting Follow-Up',
        'Research Phase Update',
        'Implementation Status',
    ]

    FeedbackTemplate.objects.filter(name__in=template_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_feedbacktemplate_feedbackrequest'),
    ]

    operations = [
        migrations.RunPython(create_initial_templates, remove_initial_templates),
    ]
