# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_initial_feedback_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktemplate',
            name='is_write_protected',
            field=models.BooleanField(default=False, help_text='Prevent users from editing or deleting this template'),
        ),
    ]
